### ISSUE TITLE
Built images not shown in CI logs for ‘List docker images’ steps

### ISSUE THREAD

**Issue by joeltimothyoh** [theohbrothers/Generate-DockerImageVariants#58]
Curious as to why this is so.

Examples:

- https://github.com/theohbrothers/docker-packer/runs/4185691779?check_suite_focus=true
- https://github.com/theohbrothers/docker-powershell/runs/4144470106?check_suite_focus=true

**Comment by leojonathanoh** [comment]
when using `docker buildx` it's no longer the same as using `docker build`. each build runs inside a VM so i think there needs a special syntax to list the built images.

**Comment by leojonathanoh** [comment]
Perhaps one may use `docker buildx imagetools image` to list arch builds  https://docs.docker.com/engine/reference/commandline/buildx_imagetools/, . But to get the same output as `docker build`, doesn't seem possible at least not that i know of.

**Comment by joeltimothyoh** [comment]
It’s strange this negation was never spotted as though the CI logs were never looked through. @leojonathanoh

**Comment by leojonathanoh** [comment]
i have always looked through, but i never had time to ensure the CI jobs had outputs like the traditional `docker build`, because as i said it is not possible with `docker buildx`. It's not that the output was omitted or neglected, but that there was no way to output using docker CLI at least at the moment.

Even with `docker buildx imagetools <image>` (which is still a docker CLI plugin as of yet), that command only lists the architectures of each image, and their image digests, but no way as what one would expect with `docker images`.

**Comment by leojonathanoh** [comment]
@joeltimothyoh is this still an issue? we could add `docker buildx imagetools <image>`, but i'd say it won't be very helpful at all, since `docker buildx` itself already shows the detail logs for each archs being built.

If we decide not to implement this, we can close this.

**Comment by leojonathanoh** [comment]
Closing. `docker buildx` cannot list the images because it's using the `docker-container` builder type, as explained earlier.
